package quizweb.domain.repository.mapper.base;

import org.apache.ibatis.annotations.Mapper;
import quizweb.domain.repository.entity.Quiz;

@Mapper
public interface QuizMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz
     *
     * @mbg.generated Tue Jan 25 12:51:21 UTC 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz
     *
     * @mbg.generated Tue Jan 25 12:51:21 UTC 2022
     */
    int insert(Quiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz
     *
     * @mbg.generated Tue Jan 25 12:51:21 UTC 2022
     */
    int insertSelective(Quiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz
     *
     * @mbg.generated Tue Jan 25 12:51:21 UTC 2022
     */
    Quiz selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz
     *
     * @mbg.generated Tue Jan 25 12:51:21 UTC 2022
     */
    int updateByPrimaryKeySelective(Quiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz
     *
     * @mbg.generated Tue Jan 25 12:51:21 UTC 2022
     */
    int updateByPrimaryKey(Quiz record);
}