package quizweb.domain.repository.mapper.base;

import org.apache.ibatis.annotations.Mapper;
import quizweb.domain.repository.entity.StagingQuiz;

@Mapper
public interface StagingQuizMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_quiz
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    int deleteByPrimaryKey(Long quizId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_quiz
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    int insert(StagingQuiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_quiz
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    int insertSelective(StagingQuiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_quiz
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    StagingQuiz selectByPrimaryKey(Long quizId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_quiz
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    int updateByPrimaryKeySelective(StagingQuiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_quiz
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    int updateByPrimaryKey(StagingQuiz record);
}