package quizweb.domain.repository.mapper.base;

import org.apache.ibatis.annotations.Mapper;
import quizweb.domain.repository.entity.StagingChoice;

@Mapper
public interface StagingChoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_choice
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    int deleteByPrimaryKey(Long choiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_choice
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    int insert(StagingChoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_choice
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    int insertSelective(StagingChoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_choice
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    StagingChoice selectByPrimaryKey(Long choiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_choice
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    int updateByPrimaryKeySelective(StagingChoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_choice
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    int updateByPrimaryKeyWithBLOBs(StagingChoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_choice
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    int updateByPrimaryKey(StagingChoice record);
}