package quizweb.domain.repository.mapper.base;

import org.apache.ibatis.annotations.Mapper;
import quizweb.domain.repository.entity.StagingQuestion;

@Mapper
public interface StagingQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_question
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    int deleteByPrimaryKey(Long questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_question
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    int insert(StagingQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_question
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    int insertSelective(StagingQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_question
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    StagingQuestion selectByPrimaryKey(Long questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_question
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    int updateByPrimaryKeySelective(StagingQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_question
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    int updateByPrimaryKeyWithBLOBs(StagingQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staging_question
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    int updateByPrimaryKey(StagingQuestion record);
}