package quizweb.domain.repository.entity;

public class Choice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.id
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.question_id
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.quiz_id
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    private Long quizId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.selection_no
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    private Integer selectionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.correct_flg
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    private Boolean correctFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.create_userid
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    private Long createUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choice.content
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.id
     *
     * @return the value of choice.id
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.id
     *
     * @param id the value for choice.id
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.question_id
     *
     * @return the value of choice.question_id
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.question_id
     *
     * @param questionId the value for choice.question_id
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.quiz_id
     *
     * @return the value of choice.quiz_id
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public Long getQuizId() {
        return quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.quiz_id
     *
     * @param quizId the value for choice.quiz_id
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public void setQuizId(Long quizId) {
        this.quizId = quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.selection_no
     *
     * @return the value of choice.selection_no
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public Integer getSelectionNo() {
        return selectionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.selection_no
     *
     * @param selectionNo the value for choice.selection_no
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public void setSelectionNo(Integer selectionNo) {
        this.selectionNo = selectionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.correct_flg
     *
     * @return the value of choice.correct_flg
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public Boolean getCorrectFlg() {
        return correctFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.correct_flg
     *
     * @param correctFlg the value for choice.correct_flg
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public void setCorrectFlg(Boolean correctFlg) {
        this.correctFlg = correctFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.create_userid
     *
     * @return the value of choice.create_userid
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public Long getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.create_userid
     *
     * @param createUserid the value for choice.create_userid
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public void setCreateUserid(Long createUserid) {
        this.createUserid = createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choice.content
     *
     * @return the value of choice.content
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choice.content
     *
     * @param content the value for choice.content
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public void setContent(String content) {
        this.content = content;
    }
}