package quizweb.domain.repository.entity;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.quiz_id
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    private Long quizId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.num
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.name
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.create_userid
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    private Long createUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.content
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.comment
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.choiceType
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    private String choicetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.quiz_id
     *
     * @return the value of question.quiz_id
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    public Long getQuizId() {
        return quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.quiz_id
     *
     * @param quizId the value for question.quiz_id
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    public void setQuizId(Long quizId) {
        this.quizId = quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.num
     *
     * @return the value of question.num
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.num
     *
     * @param num the value for question.num
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.name
     *
     * @return the value of question.name
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.name
     *
     * @param name the value for question.name
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.create_userid
     *
     * @return the value of question.create_userid
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    public Long getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.create_userid
     *
     * @param createUserid the value for question.create_userid
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    public void setCreateUserid(Long createUserid) {
        this.createUserid = createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.content
     *
     * @return the value of question.content
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.content
     *
     * @param content the value for question.content
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.comment
     *
     * @return the value of question.comment
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.comment
     *
     * @param comment the value for question.comment
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.choiceType
     *
     * @return the value of question.choiceType
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    public String getChoicetype() {
        return choicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.choiceType
     *
     * @param choicetype the value for question.choiceType
     *
     * @mbg.generated Sat Mar 18 08:57:41 UTC 2023
     */
    public void setChoicetype(String choicetype) {
        this.choicetype = choicetype;
    }
}