package quizweb.domain.repository.entity;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column question.id
     *
     * @mbg.generated Sun May 16 03:01:42 UTC 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column question.quiz_id
     *
     * @mbg.generated Sun May 16 03:01:42 UTC 2021
     */
    private Long quizId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column question.num
     *
     * @mbg.generated Sun May 16 03:01:42 UTC 2021
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column question.name
     *
     * @mbg.generated Sun May 16 03:01:42 UTC 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column question.content
     *
     * @mbg.generated Sun May 16 03:01:42 UTC 2021
     */
    private String content;

    private String choiceType;

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated Sun May 16 03:01:42 UTC 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated Sun May 16 03:01:42 UTC 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column question.quiz_id
     *
     * @return the value of question.quiz_id
     *
     * @mbg.generated Sun May 16 03:01:42 UTC 2021
     */
    public Long getQuizId() {
        return quizId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column question.quiz_id
     *
     * @param quizId the value for question.quiz_id
     *
     * @mbg.generated Sun May 16 03:01:42 UTC 2021
     */
    public void setQuizId(Long quizId) {
        this.quizId = quizId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column question.num
     *
     * @return the value of question.num
     *
     * @mbg.generated Sun May 16 03:01:42 UTC 2021
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column question.num
     *
     * @param num the value for question.num
     *
     * @mbg.generated Sun May 16 03:01:42 UTC 2021
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column question.name
     *
     * @return the value of question.name
     *
     * @mbg.generated Sun May 16 03:01:42 UTC 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column question.name
     *
     * @param name the value for question.name
     *
     * @mbg.generated Sun May 16 03:01:42 UTC 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column question.content
     *
     * @return the value of question.content
     *
     * @mbg.generated Sun May 16 03:01:42 UTC 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column question.content
     *
     * @param content the value for question.content
     *
     * @mbg.generated Sun May 16 03:01:42 UTC 2021
     */
    public void setContent(String content) {
        this.content = content;
    }

    public String getChoiceType() {
        return choiceType;
    }

    public void setChoiceType(String choiceType) {
        this.choiceType = choiceType;
    }

}