package quizweb.domain.repository.entity;

public class Quiz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.id
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.crete_userid
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    private Long creteUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.title
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.category
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.tag
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    private String tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.id
     *
     * @return the value of quiz.id
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.id
     *
     * @param id the value for quiz.id
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.crete_userid
     *
     * @return the value of quiz.crete_userid
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public Long getCreteUserid() {
        return creteUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.crete_userid
     *
     * @param creteUserid the value for quiz.crete_userid
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public void setCreteUserid(Long creteUserid) {
        this.creteUserid = creteUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.title
     *
     * @return the value of quiz.title
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.title
     *
     * @param title the value for quiz.title
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.category
     *
     * @return the value of quiz.category
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.category
     *
     * @param category the value for quiz.category
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.tag
     *
     * @return the value of quiz.tag
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.tag
     *
     * @param tag the value for quiz.tag
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public void setTag(String tag) {
        this.tag = tag;
    }
}