package quizweb.domain.repository.entity;

public class Selection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.id
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.question_id
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    private Long questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.selection_no
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    private Integer selectionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.correct_flg
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    private Boolean correctFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column selection.content
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.id
     *
     * @return the value of selection.id
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.id
     *
     * @param id the value for selection.id
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.question_id
     *
     * @return the value of selection.question_id
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.question_id
     *
     * @param questionId the value for selection.question_id
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.selection_no
     *
     * @return the value of selection.selection_no
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public Integer getSelectionNo() {
        return selectionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.selection_no
     *
     * @param selectionNo the value for selection.selection_no
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public void setSelectionNo(Integer selectionNo) {
        this.selectionNo = selectionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.correct_flg
     *
     * @return the value of selection.correct_flg
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public Boolean getCorrectFlg() {
        return correctFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.correct_flg
     *
     * @param correctFlg the value for selection.correct_flg
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public void setCorrectFlg(Boolean correctFlg) {
        this.correctFlg = correctFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column selection.content
     *
     * @return the value of selection.content
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column selection.content
     *
     * @param content the value for selection.content
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    public void setContent(String content) {
        this.content = content;
    }
}