package quizweb.domain.repository.entity;

public class StagingQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staging_question.question_id
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staging_question.quiz_id
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    private Long quizId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staging_question.num
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staging_question.content
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staging_question.comment
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staging_question.choiceType
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    private String choicetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staging_question.question_id
     *
     * @return the value of staging_question.question_id
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staging_question.question_id
     *
     * @param questionId the value for staging_question.question_id
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staging_question.quiz_id
     *
     * @return the value of staging_question.quiz_id
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public Long getQuizId() {
        return quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staging_question.quiz_id
     *
     * @param quizId the value for staging_question.quiz_id
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public void setQuizId(Long quizId) {
        this.quizId = quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staging_question.num
     *
     * @return the value of staging_question.num
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staging_question.num
     *
     * @param num the value for staging_question.num
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staging_question.content
     *
     * @return the value of staging_question.content
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staging_question.content
     *
     * @param content the value for staging_question.content
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staging_question.comment
     *
     * @return the value of staging_question.comment
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staging_question.comment
     *
     * @param comment the value for staging_question.comment
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staging_question.choiceType
     *
     * @return the value of staging_question.choiceType
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public String getChoicetype() {
        return choicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staging_question.choiceType
     *
     * @param choicetype the value for staging_question.choiceType
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public void setChoicetype(String choicetype) {
        this.choicetype = choicetype;
    }
}