package quizweb.domain.repository.entity;

public class StagingQuiz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staging_quiz.quiz_id
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    private Long quizId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staging_quiz.title
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staging_quiz.description
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staging_quiz.thumbnail
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    private String thumbnail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staging_quiz.quiz_id
     *
     * @return the value of staging_quiz.quiz_id
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public Long getQuizId() {
        return quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staging_quiz.quiz_id
     *
     * @param quizId the value for staging_quiz.quiz_id
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public void setQuizId(Long quizId) {
        this.quizId = quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staging_quiz.title
     *
     * @return the value of staging_quiz.title
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staging_quiz.title
     *
     * @param title the value for staging_quiz.title
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staging_quiz.description
     *
     * @return the value of staging_quiz.description
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staging_quiz.description
     *
     * @param description the value for staging_quiz.description
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staging_quiz.thumbnail
     *
     * @return the value of staging_quiz.thumbnail
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staging_quiz.thumbnail
     *
     * @param thumbnail the value for staging_quiz.thumbnail
     *
     * @mbg.generated Mon Apr 17 16:14:48 UTC 2023
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }
}