package quizweb.domain.repository.entity;

public class StagingChoice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staging_choice.choice_id
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    private Long choiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staging_choice.quiz_id
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    private Long quizId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staging_choice.question_id
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staging_choice.selection_no
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    private Integer selectionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staging_choice.correct_flg
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    private Boolean correctFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staging_choice.content
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staging_choice.choice_id
     *
     * @return the value of staging_choice.choice_id
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    public Long getChoiceId() {
        return choiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staging_choice.choice_id
     *
     * @param choiceId the value for staging_choice.choice_id
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    public void setChoiceId(Long choiceId) {
        this.choiceId = choiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staging_choice.quiz_id
     *
     * @return the value of staging_choice.quiz_id
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    public Long getQuizId() {
        return quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staging_choice.quiz_id
     *
     * @param quizId the value for staging_choice.quiz_id
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    public void setQuizId(Long quizId) {
        this.quizId = quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staging_choice.question_id
     *
     * @return the value of staging_choice.question_id
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staging_choice.question_id
     *
     * @param questionId the value for staging_choice.question_id
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staging_choice.selection_no
     *
     * @return the value of staging_choice.selection_no
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    public Integer getSelectionNo() {
        return selectionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staging_choice.selection_no
     *
     * @param selectionNo the value for staging_choice.selection_no
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    public void setSelectionNo(Integer selectionNo) {
        this.selectionNo = selectionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staging_choice.correct_flg
     *
     * @return the value of staging_choice.correct_flg
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    public Boolean getCorrectFlg() {
        return correctFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staging_choice.correct_flg
     *
     * @param correctFlg the value for staging_choice.correct_flg
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    public void setCorrectFlg(Boolean correctFlg) {
        this.correctFlg = correctFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staging_choice.content
     *
     * @return the value of staging_choice.content
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staging_choice.content
     *
     * @param content the value for staging_choice.content
     *
     * @mbg.generated Sat Apr 15 12:20:57 UTC 2023
     */
    public void setContent(String content) {
        this.content = content;
    }
}