package quizweb.domain.repository.entity;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.id
     *
     * @mbg.generated Sat Oct 16 02:39:48 UTC 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag
     *
     * @mbg.generated Sat Oct 16 02:39:48 UTC 2021
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.num
     *
     * @mbg.generated Sat Oct 16 02:39:48 UTC 2021
     */
    private Long num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.id
     *
     * @return the value of tag.id
     *
     * @mbg.generated Sat Oct 16 02:39:48 UTC 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.id
     *
     * @param id the value for tag.id
     *
     * @mbg.generated Sat Oct 16 02:39:48 UTC 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag
     *
     * @return the value of tag.tag
     *
     * @mbg.generated Sat Oct 16 02:39:48 UTC 2021
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag
     *
     * @param tag the value for tag.tag
     *
     * @mbg.generated Sat Oct 16 02:39:48 UTC 2021
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.num
     *
     * @return the value of tag.num
     *
     * @mbg.generated Sat Oct 16 02:39:48 UTC 2021
     */
    public Long getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.num
     *
     * @param num the value for tag.num
     *
     * @mbg.generated Sat Oct 16 02:39:48 UTC 2021
     */
    public void setNum(Long num) {
        this.num = num;
    }
}