package quizweb.domain.repository.mapper;

import quizweb.domain.repository.entity.Quiz;

public interface QuizMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    int insert(Quiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    int insertSelective(Quiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    Quiz selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    int updateByPrimaryKeySelective(Quiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quiz
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    int updateByPrimaryKey(Quiz record);
}