package quizweb.domain.repository.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import quizweb.domain.repository.entity.QuizTagging;

@Mapper
public interface QuizTaggingMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table quiz_tagging
     *
     * @mbg.generated Sat Oct 16 07:15:00 UTC 2021
     */
    int insert(QuizTagging record);

    int insertList(List<QuizTagging> record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table quiz_tagging
     *
     * @mbg.generated Sat Oct 16 07:15:00 UTC 2021
     */
    int insertSelective(QuizTagging record);
}