package quizweb.domain.repository.mapper;

import quizweb.domain.repository.entity.Selection;

public interface SelectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selection
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selection
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    int insert(Selection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selection
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    int insertSelective(Selection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selection
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    Selection selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selection
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    int updateByPrimaryKeySelective(Selection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selection
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    int updateByPrimaryKeyWithBLOBs(Selection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selection
     *
     * @mbggenerated Thu Apr 08 18:17:38 UTC 2021
     */
    int updateByPrimaryKey(Selection record);
}