package quizweb.domain.repository.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import quizweb.domain.repository.entity.Tag;

@Mapper
public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table tag
     *
     * @mbg.generated Sat Oct 16 02:39:48 UTC 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table tag
     *
     * @mbg.generated Sat Oct 16 02:39:48 UTC 2021
     */
    int insert(Tag record);

    int insertList(@Param("list") List<Tag> list);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table tag
     *
     * @mbg.generated Sat Oct 16 02:39:48 UTC 2021
     */
    int insertSelective(Tag record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table tag
     *
     * @mbg.generated Sat Oct 16 02:39:48 UTC 2021
     */
    Tag selectByPrimaryKey(Long id);

    List<Tag> selectListByContentList(List<String> list);

    Tag selectByTagContent(String content);

    List<Tag> selectByPrefix(String prefix);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table tag
     *
     * @mbg.generated Sat Oct 16 02:39:48 UTC 2021
     */
    int updateByPrimaryKeySelective(Tag record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table tag
     *
     * @mbg.generated Sat Oct 16 02:39:48 UTC 2021
     */
    int updateByPrimaryKey(Tag record);

    int updateNum(List<Long> updateList);

}